# Site settings
title:          MommaFinds
description:    "Helping Mommas find the happy medium."
baseurl:        "/"
url:            "https://www.mommafinds.com"

# Author
author:
  name:         Kerry Guard
  email:        mommafinds2017@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      pretty
paginate:       5
